### ISSUE TITLE
JQuerry 1.8.1  search error items and mobs

### ISSUE THREAD

**Issue by Megasantos** [missxantara/fluxcp-ra#2]
Not being able to use search for items and mobs with updating the JQuery 1.8.1

https://github.com/missxantara/fluxcp-ra/commit/b34a49d2d0d734e01ae7bb6e019c9e6aaa86591e
# edit

Concerted error is missing a variable, so maybe add manually.

**Comment by missxantara** [comment]
Hi, thanks for reporting an issue. From your edit, it seems you found a solution? Which variable is missing?

**Comment by Megasantos** [comment]
Your are correct my mistake was to pick up xantara site, sorry for the incident.

**Comment by missxantara** [comment]
Umm.. not sure if I understood correctly, but I think this issue is **invalid**. If I misunderstood, please do let me know.
