### ISSUE TITLE
New Revisions SQL Schemas Problems

### ISSUE THREAD

**Issue by relzz-v0** [missxantara/fluxcp-ra#6]
Im trying to install in localhost and i configured all correctly and checked my DB to don't have duplicates.. but i got this error on the most recent rev
The version of the modules show very big.. shoulnd't be: 20081109
instead of this?:
cp_banlog    20081109093448 None

This is the Debug msg i got:
Warning: file_get_contents() expects parameter 1 to be a valid path, array given in C:\xampp\htdocs\panel\lib\Flux\Installer\Schema.php on line 102
Critical Error

An error was encountered during the lifetime of the application.

This could be due to a variety of problems, such as a bug in the application.

However, normally it is caused by misconfiguration.

Exception Details

Error: Flux_Error

Message: Critical MySQL error in Installer/Updater: Query was empty

File: C:\xampp\htdocs\panel\lib\Flux\Installer\Schema.php:133

File    Line    Function/Method
C:\xampp\htdocs\panel\lib\Flux\Installer\Schema.php 157 Flux_Installer_Schema::install()
C:\xampp\htdocs\panel\lib\Flux\Installer.php    69  Flux_Installer_Schema::update()
C:\xampp\htdocs\panel\modules\install\index.php 31  Flux_Installer::updateAll()
C:\xampp\htdocs\panel\lib\Flux\Template.php 337 include()
C:\xampp\htdocs\panel\lib\Flux\Dispatcher.php   168 Flux_Template::render()
C:\xampp\htdocs\panel\index.php 177 Flux_Dispatcher::dispatch()
Exception Trace As String
#0 C:\xampp\htdocs\panel\lib\Flux\Installer\Schema.php(157): Flux_Installer_Schema->install('20080928225124')
#1 C:\xampp\htdocs\panel\lib\Flux\Installer.php(69): Flux_Installer_Schema->update()
#2 C:\xampp\htdocs\panel\modules\install\index.php(31): Flux_Installer->updateAll()
#3 C:\xampp\htdocs\panel\lib\Flux\Template.php(337): include('C:\xampp\htdocs...')
#4 C:\xampp\htdocs\panel\lib\Flux\Dispatcher.php(168): Flux_Template->render()
#5 C:\xampp\htdocs\panel\index.php(177): Flux_Dispatcher->dispatch(Array)
#6 {main}

**Comment by missxantara** [comment]
Thanks for creating an issue report. 

The version report is correct. It is in the form of year/month/day/hr/min/sec. 

As for the actual error, please check if you the following file
=>  C:\xampp\htdocs\panel\data\schemas\logindb\cp_banlog.20080928225124.sql 

and that the contents matches the ones found in
=>  https://github.com/missxantara/fluxcp-ra/blob/master/data/schemas/logindb/cp_banlog.20080928225124.sql

**Comment by relzz-v0** [comment]
I've reinstalled it again(100% Clean) and the same error.. is there..
![Dibujo](https://f.cloud.github.com/assets/2993425/231820/f6514d0e-8714-11e2-99de-fcc1b9f9cd2b.PNG)

**Comment by missxantara** [comment]
I can't reproduce... I just tried a clean install and it worked fine for me.

If you want, we can chat on MSN (missxantara@gmail.com) / Skype (live:missxantara) and perhaps Teamviewer to check what is wrong?

**Comment by relzz-v0** [comment]
I added you to Skype .. well let me try 1 more time.. ill record all what i do this time :P

**Comment by relzz-v0** [comment]
Here is a video of what i do when the error appears:
http://youtu.be/ofA4aGLNObc
My PC is slow.. and i recorded on MPEG mode so it's more slow xD check it =)

**Comment by relzz-v0** [comment]
I've tried on 2 webhostings with a fresh install and still same problem..
This doesn't happened before you renamed the sql schema files o.o

**Comment by missxantara** [comment]
I've tried installing with a new database, new checkout/clone of GIT, clean website directory.. and it works fine for me.. 

But I don't think you are the only one having troubles so there must be something wrong. I just don't understand why I can't seem to reproduce. 

I haven't seen you on Skype either.. I'm on now if you can go online
