### ISSUE TITLE
guild emblem doesn't show on latest revision.

### ISSUE THREAD

**Issue by bgamez23** [missxantara/fluxcp-ra#7]
before i update my fluxcp the guild emblem works fine. but not i can't see any guild emblem.

**Comment by bgamez23** [comment]
bump

**Comment by missxantara** [comment]
Tested with the latest code, and it works fine for me... I'm pretty sure I didn't change any code regarding guild emblems being shown =x

Please try with a clean checkout/clone of the repository on your current host. If you still run into problems, please let me know.

**Comment by missxantara** [comment]
No response in 3 days so I will be closing this and marking as invalid. I was also helping someone with installing their FluxCP and guild emblems showed up for them fine.

As always, if you continue to have problems or find any bugs, feel free to open a new ticket or contact me for support.
